### ISSUE TITLE
Error "Cannot call method 'pull' of undefined"

### ISSUE THREAD

**Issue by michaelryancaputo** [cristiandouce/mongoose-voting#10]
I can't seem to figure out why I keep getting this error. I'm trying to use this with Hapi 7.5.3. It happens with both downvote and upvote.

    TypeError: Uncaught error: Cannot call method 'pull' of undefined
        at model.downvote (/Users/mike/Projects/normbox/node_modules/mongoose-voting/index.js:49:24)
        at Promise.<anonymous> (/Users/mike/Projects/normbox/api/controllers/voting.js:321:18)
        at Promise.<anonymous> (/Users/mike/Projects/normbox/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
        at Promise.emit (events.js:95:17)
        at Promise.emit (/Users/mike/Projects/normbox/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
        at Promise.fulfill (/Users/mike/Projects/normbox/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
        at /Users/mike/Projects/normbox/node_modules/mongoose/lib/query.js:1394:13
        at model.Document.init (/Users/mike/Projects/normbox/node_modules/mongoose/lib/document.js:250:11)
        at completeOne (/Users/mike/Projects/normbox/node_modules/mongoose/lib/query.js:1392:10)
        at Object.cb (/Users/mike/Projects/normbox/node_modules/mongoose/lib/query.js:1151:11)

**Comment by michaelryancaputo** [comment]
My bad, already had a field in the DB called "vote"
