### ISSUE TITLE
.voted(user) throws error: "Cannot read property 'positive' of undefined"

### ISSUE THREAD

**Issue by michaelryancaputo** [cristiandouce/mongoose-voting#11]
I'm getting this error when trying to use doc.voted(user) to check if a user has voted on a document:

                TypeError: Uncaught error: Cannot read property 'positive' of undefined
                at Object.upvoted (/Users/mike/Projects/normbox/node_modules/mongoose-voting/index.js:75:24)
                at model.voted (/Users/mike/Projects/normbox/node_modules/mongoose-voting/index.js:91:27)
                at Promise.<anonymous> (/Users/mike/Projects/normbox/api/controllers/voting.js:200:20)
                at Promise.<anonymous> (/Users/mike/Projects/normbox/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
                at Promise.emit (events.js:95:17)
                at Promise.emit (/Users/mike/Projects/normbox/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
                at Promise.fulfill (/Users/mike/Projects/normbox/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
                at /Users/mike/Projects/normbox/node_modules/mongoose/lib/query.js:1394:13
                at model.Document.init (/Users/mike/Projects/normbox/node_modules/mongoose/lib/document.js:250:11)
                at completeOne (/Users/mike/Projects/normbox/node_modules/mongoose/lib/query.js:1392:10)

Doesn't seem to work if I do a _.contains(doc,userId) either. Any idea?

**Comment by cristiandouce** [comment]
Could you share your schema? I think this may be related to: #10 but can't confirm now.

As you can see, I save values in the schema with the following format
```js
schema.add({
    vote: {
      positive: [{ type: ObjectId, ref: voterModelName }],
      negative: [{ type: ObjectId, ref: voterModelName }]
    }
});
```
> https://github.com/cristiandouce/mongoose-voting/blob/master/index.js#L27-L32

If you are indeed using the `.vote` path for something else, that may be the issue.

Thanks!

**Comment by michaelryancaputo** [comment]
@cristiandouce Thanks for the reply, here it is:

	var songData = {
		key: {type: String},
		name: {type: String},
		artist: {type: String},
		icon: {type: String},
		bigIcon: {type: String},
		bigIcon1200: {type: String},
		addedById: {type: Schema.Types.ObjectId, ref: 'User'},
		addedBy: {type: String},
		voteCount : {type: Number, default: 0}
	};
	/**
	 * Thing Schema
	 */
	var QueuedSongsSchema = new Schema(songData);
	QueuedSongsSchema.plugin(voting, { ref: 'User' });
	mongoose.model('QueuedSongs', QueuedSongsSchema );

I had the same thought, however after I closed #10 i removed the 'vote' field from my schema and it seemed to work.

Any other insight?

**Comment by cristiandouce** [comment]
Could it be that some old documents have that `vote` path with a value different from what mongoose-voting expects, maybe a number or a string.

You may have to migrate old document's attributes. Could that be?

**Comment by michaelryancaputo** [comment]
I dropped the database and started fresh, still same result:

          Debug: hapi, internal, implementation, error 
              TypeError: Uncaught error: Cannot read property 'positive' of undefined
              at Object.upvoted (/Users/mike/Projects/normbox/node_modules/mongoose-voting/index.js:75:24)
              at model.voted (/Users/mike/Projects/normbox/node_modules/mongoose-voting/index.js:91:27)
              at Promise.<anonymous> (/Users/mike/Projects/normbox/api/controllers/voting.js:198:25)
              at Promise.<anonymous> (/Users/mike/Projects/normbox/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
              at Promise.emit (events.js:95:17)
              at Promise.emit (/Users/mike/Projects/normbox/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
              at Promise.fulfill (/Users/mike/Projects/normbox/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
              at /Users/mike/Projects/normbox/node_modules/mongoose/lib/query.js:1394:13
              at model.Document.init (/Users/mike/Projects/normbox/node_modules/mongoose/lib/document.js:250:11)
              at completeOne (/Users/mike/Projects/normbox/node_modules/mongoose/lib/query.js:1392:10)

**Comment by cristiandouce** [comment]
mongoose version?

**Comment by michaelryancaputo** [comment]
Currently have v3.8.21. This is my package.json deps in case that is any help:

	  "dependencies": {
	    "async": "^0.9.0",
	    "base64": "^2.1.0",
	    "bcryptjs": "^2.1.0",
	    "good": "^3.1.1",
	    "gulp": "^3.8.10",
	    "gulp-autoprefixer": "^2.0.0",
	    "gulp-bower-files": "^0.2.7",
	    "gulp-concat": "^2.4.2",
	    "gulp-minify-css": "^0.3.11",
	    "gulp-nodemon": "^1.0.4",
	    "gulp-ruby-sass": "^0.7.1",
	    "gulp-uglify": "^1.0.2",
	    "handlebars": "^2.0.0",
	    "hapi": "^7.1.1",
	    "hapi-cache-buster": "^0.2.0",
	    "hapi-mongodb": "^2.2.0",
	    "hapi-mongoose-connector": "^1.0.0",
	    "hapi-named-routes": "^0.2.0",
	    "hapi-passport": "0.0.5",
	    "joi": "^4.7.0",
	    "jwt-simple": "^0.2.0",
	    "lodash": "^2.4.1",
	    "lodash-node": "^2.4.1",
	    "lout": "^5.1.1",
	    "main-bower-files": "^2.4.1",
	    "moment": "^2.9.0",
	    "mongoose": "^3.8.14",
	    "mongoose-voting": "^0.2.0",
	    "passport-google-oauth": "^0.1.5",
	    "path": "^0.11.14",
	    "qs": "^2.3.3",
	    "querystring": "^0.2.0",
	    "rdio": "^1.5.2",
	    "request": "^2.51.0",
	    "require-directory": "^2.0.0",
	    "satellizer": "^0.8.8",
	    "socket.io": "^1.2.1",
	    "swig": "^1.4.2",
	    "url": "^0.10.1",
	    "yar": "^2.4.0"
	  },

**Comment by michaelryancaputo** [comment]
@cristiandouce Any word about this? Can you make a suggestion for what version of Mongoose I should be using?

**Comment by cristiandouce** [comment]
I'm sorry. I didn't really have the time to check it. If you can provide with a sample seed I could just download and debug I might get an answer later today.

If you are concerned about the mongoose version, try downgrading mongoose to the version used in the tests.

I'll check that out later!

Thanks for the patience.

**Comment by michaelryancaputo** [comment]
I haven't had any luck with this

**Comment by monad98** [comment]
same problem here.

**Comment by monad98** [comment]
I changed code like this. and seems fine now.

schema.methods.voted = function voted(user) {
    if (user._id) {
      return schema.methods.voted.call(this, user._id);
    };

    return schema.methods.upvoted.call(this, user) || schema.methods.downvoted.call(this, user);
  }

**Comment by michaelryancaputo** [comment]
@monad98 I'd suggest submitting a PR if you have it working
